reader-dict/monolingual

scripts/lang/fr/__init__.py, tests/test_fr.py
Ex: https://fr.wiktionary.org/wiki/lune
=> [FR] Better handle the 'date' template (closes #196)

scripts/lang/fr/__init__.py
=> fix #232: [FR] support l template

scripts/lang/fr/__init__.py, tests/test_fr.py
Ex: https://fr.wiktionary.org/wiki/boursi%C3%A8re
Ex: https://fr.wiktionary.org/wiki/r%C3%A9glage
=> [FR] Handle empty date template (closes #240)

scripts/lang/fr/__init__.py
=> fix #239, #251 : Handle 'agglutination' and 'univerbation' template

scripts/lang/fr/__init__.py
Ex: https://fr.wiktionary.org/wiki/classificateur
=> [FR] Handle the 'zh-lien' template (closes #273)

scripts/lang/fr/__init__.py
Ex: https://fr.wiktionary.org/wiki/ACAB
=> [FR] Handle 'acronyme' template (closes #285)

scripts/lang/fr/__init__.py
Ex: https://fr.wiktionary.org/wiki/main
=> [FR] Ignore the '?' template (closes #303)

scripts/lang/fr/__init__.py
=> fix #323: [FR] Handle 'cit_réf' / 'cit réf' template

scripts/lang/en/__init__.py, scripts/transliterator.py, tests/data/en/us.wiki, tests/data/fr/corps portant.wiki, tests/test_en.py
Ex: https://en.wiktionary.org/wiki/Iraq
=> [EN] Enhance support for 'm' and 'l' templates (closes #347)

scripts/lang/fr/__init__.py
=> [FR] Ignore '*', 'Accord des couleurs' and ibid' templates

scripts/lang/fr/__init__.py, tests/test_fr.py
Also fix 'o', 'numéro', '1er' templates
=> fix #354: [FR] Support for e/ème/er/ère templates

scripts/lang/en/__init__.py
=> fix #415: [EN] Support 'named-after' template

.github/workflows/auto-updates.yml, requirements.txt, tests/test_3_convert.py, wikidict/convert.py
--convert: Generate dict-LOCALE.df
And not dict-LOCALE-LOCALE.df.
=> Publish StarDict files

wikidict/lang/fr/__init__.py
Ex: https://fr.wiktionary.org/wiki/DH
=> fix #503: [FR] Ignore the 'lien-ancre-étym' template

wikidict/lang/fr/__init__.py, wikidict/lang/fr/template_handlers.py
Ex: https://fr.wiktionary.org/wiki/DH
=> fix #504: [FR] Fix handling of the 'abréviation' template

tests/test_ca.py, wikidict/lang/ca/__init__.py
Ex: https://ca.wiktionary.org/wiki/%E0%A4%9C%E0%A4%BC
=> fix #522: [CA] Handle the 'pron' template

tests/test_ca.py, wikidict/lang/ca/__init__.py
Ex: https://ca.wiktionary.org/wiki/Catllar
=> fix #516: [CA] Handle the 'doblet' template

wikidict/lang/fr/template_handlers.py
Ex: https://fr.wiktionary.org/wiki/%C3%AAtre
=> fix #536: [FR] Better support of 'lien' template

tests/test_fr.py, wikidict/lang/fr/template_handlers.py
Ex: https://fr.wiktionary.org/wiki/suivre
=> fix #539: [FR] Better support of 'étyl' template

tests/test_pt.py, wikidict/lang/pt/__init__.py
Ex: https://pt.wiktionary.org/wiki/saldo
=> fix #547: [PT] Better handling of the 'llietimo' template

wikidict/lang/fr/__init__.py, wikidict/lang/fr/template_handlers.py
Ex: https://fr.wiktionary.org/wiki/imp%C3%A9rial
=> fix #560: [FR] Review handling of the 'siècle2' template

wikidict/lang/defaults.py, wikidict/utils.py
Ex:
- https://fr.wiktionary.org/wiki/Apremont
- https://fr.wiktionary.org/wiki/Aridam%C3%A9rique
- https://fr.wiktionary.org/wiki/s%C3%A9ga
=> fix #568: Fix handling of imbricated templates 'w' -> 'pc'

tests/test_fr.py, wikidict/lang/fr/__init__.py
Ex: https://fr.wiktionary.org/wiki/d%C3%A9vanagari
=> fix #343: [FR] Add support for the 'Deva' template

tests/test_pt.py, wikidict/lang/pt/__init__.py, wikidict/user_functions.py
Ex:
- https://pt.wiktionary.org/wiki/Ernestino
- https://pt.wiktionary.org/wiki/relo
- https://pt.wiktionary.org/wiki/pentecostal
=> fix #594: [PT] Words outside the 'escopos' list should not be lowercased

tests/test_fr.py, wikidict/lang/fr/__init__.py
Ex: https://fr.wiktionary.org/wiki/noir_animal
=> fix #592: [FR] Review output of 'couleur' template

wikidict/lang/fr/template_handlers.py
=> fix #572: [FR] Tweak handling of the 'composé de' template

wikidict/lang/__init__.py, wikidict/lang/sv.py, wikidict/render.py
Ex: https://sv.wiktionary.org/wiki/G%C3%B6tet
=> fix #611: [SV] Ignore the 'citat' template

tests/test_sv.py, wikidict/lang/sv.py, wikidict/user_functions.py
Added the `strike()` function for the occasion.
=> fix #613: [SV] Add support for 'ö' templates

wikidict/lang/fr/__init__.py, wikidict/lang/fr/template_handlers.py
=> fix #632: [FR] Improve support of 'apocope' template

wikidict/lang/fr/__init__.py
=> fix #640: [FR] Ignore 'laé' template, support 'obsolète' and 'Braille'

tests/test_en.py, wikidict/lang/en/__init__.py
Ex: https://en.wiktionary.org/wiki/nepoticide
=> fix #657: [EN] Add support for the 'glossary' template

wikidict/lang/fr/template_handlers.py
=> fix #683: [FR] Better support for 'siècle' template with I

wikidict/lang/fr/__init__.py, wikidict/lang/fr/template_handlers.py
Other misc. fixes. Typo in masculing, 'sens' can be empty in `composé de`, region doesn't capitalize.
New template vlatypas-pivot...
=> fix #690: [FR] 'abreviation' template doesn't have a m option despite doc

tests/test_4_check_word.py, wikidict/check_word.py
=> fix #685: check-word with if word contains subdefinitions

wikidict/lang/fr/__init__.py
Ex: https://fr.wiktionary.org/wiki/gcr
=> fix #719: [FR] Handle 'code langue' and 'nom langue' templates

wikidict/lang/fr/__init__.py, wikidict/lang/fr/template_handlers.py, wikidict/utils.py
Unit tests are passing. But the template data seems to be altered in utils.py::`clean()` so the patch does not work. I'll have a look later in the day for that part.
=> fix #680: [FR] Handle 'Lien web' template

wikidict/lang/fr/__init__.py, wikidict/lang/fr/template_handlers.py, wikidict/user_functions.py
Ex: https://fr.wiktionary.org/wiki/trente-deux_pieds
=> fix #726: [FR] Improve support for 'unité' template

tests/test_en.py, wikidict/lang/en/__init__.py
Ex: https://en.wiktionary.org/wiki/Elam
=> [EN] Support 'sub' and 'sup' templates (closes #748)

wikidict/lang/en/template_handlers.py
Also add support for langname-mention, alias of m+
=> fix #759: [EN] Handle simple calls to the 'm+' template

tests/data/fr/bath.wiki, tests/test_4_check_word.py, tests/test_4_get_word.py, tests/test_ca.py, tests/test_en.py, tests/test_es.py, tests/test_fr.py, tests/test_pt.py, wikidict/check_word.py, wikidict/convert.py, wikidict/get_word.py, wikidict/render.py, wikidict/utils.py
=> fix #198: Keep the whole etymology

wikidict/lang/en/__init__.py, wikidict/lang/fr/__init__.py, wikidict/user_functions.py
=> fix #446: Support 'zh-l' and 'zh-m' templates

tests/test_3_convert.py, tests/test_4_find_templates.py, tests/test_5_gen_dict.py, wikidict/find_templates.py
Also improved `--find-templates` by skipping templates of sections. For FR for instance, templates would list all locale sections, which is useless and add noise.
=> Get back coverage to 100%

wikidict/lang/fr/template_handlers.py
=> fix #947: [FR] Ignore ':catégorie:' from the 'cf' template

wikidict/utils.py
It is firing lot of false warnings and since we have a robust `--check-words` it is now simple to catch missing templates.
WDYT @lasconic?
=> Remove missing templates check

requirements.txt
To support all recent Python versions without compilation being required.
=> Replace marisa-try-m with marisa-try-ng

wikidict/lang/fr/__init__.py
=> Fix #209: [FR] Redirect feminine form of a noun to its masculine one

wikidict/lang/fr/__init__.py
Not really useful to render the table.
Maybe worth reconsidering when Kobo will be able to output colors :)
Fixes #1113.
=> Fix #1113: [FR] Ignore 'couleurN' template

.github/workflows/auto-updates.yml
`pyglossary --ui=none ...` works as intended (for ci / automation) since 4.1.0.
Also you may consider using language codes as part of input file name (like `dict-en-fr.df`) or change the `bookname` manually in `.ifo` file, so that GoldenDict can detect and show the 2 languages.
=> Simplify pyglossary command

.github/workflows/auto-updates.yml
Since StarDict format has no way of defining source and target languages, GoldenDict tries to detect them from `bookname`.
It's just a nice feature of GoldenDict, not a critical thing.
Here is the code that detect language codes:
[https://github.com/goldendict/goldendict/blob/master/langcoder.cc#L328](https://github.com/goldendict/goldendict/blob/8260ac87bac0681b738309a43d3392933562b958/langcoder.cc#L328)
PyGlossary automatically detects 2 language codes from input file name, and adds it to the end of StarDict `bookname`.
But looks like changing format of your `.df` file names requires a lot of changes.
So let's change `bookname` manually for now.
=> change StarDict bookname to include 2 language codes

wikidict/convert.py
The `date` metadata from the `.ifo` file now contains the Wiktionnary dump date.
Fixes #1162.
=> Add Wiktionnary snapshot in StarDict metadata

wikidict/lang/de/__init__.py
Fixes German release info text shown on the "Releases" page.
Man, all this new GH stuff _has_ gotten complicated! Tokens, expiration dates, credentials storage… Phew! Well, here we go—my first PR to this repo.
=> [DE] translate release info

requirements-tests.txt
See https://github.com/pytest-dev/pytest-cov/issues/520 and https://github.com/nedbat/coveragepy/issues/1310
=> Skip coverage 6.3.0 since it blocks tests

tests/data/de/daß.wiki, tests/data/de/trage.wiki, tests/test_de.py, wikidict/lang/de/__init__.py, wikidict/render.py
This is an initial support for variants in German. It currently parses three templates, `Grundformverweis Konj`, `Grundformverweis Dekl` and `Alte Schreibweise`, which should handle conjugated verbs, declined words and former spellings.
=> [DE] initial support for variants

tests/test_2_render.py, tests/test_ca.py, tests/test_de.py, tests/test_el.py, tests/test_en.py, tests/test_es.py, tests/test_fr.py, tests/test_it.py, tests/test_no.py, tests/test_pt.py, tests/test_ru.py, tests/test_sv.py, wikidict/find_templates.py, wikidict/lang/__init__.py, wikidict/lang/ca/__init__.py, wikidict/lang/de/__init__.py, wikidict/lang/defaults.py, wikidict/lang/el/__init__.py, wikidict/lang/en/__init__.py, wikidict/lang/es/__init__.py, wikidict/lang/fr/__init__.py, wikidict/lang/it/__init__.py, wikidict/lang/no/__init__.py, wikidict/lang/pt/__init__.py, wikidict/lang/ru/__init__.py, wikidict/lang/sv/__init__.py, wikidict/render.py, wikidict/stubs.py, wikidict/utils.py
Fixes #1174.
I reviewed completely how pronunciations were retrieved in order to tackle that task, including changing where pronunciations were looked for: before we were using the whole word wikicode, now we only use `head_sections` wikicode (faster, and more efficient).
It has the following nice side-effects (on top the having local-specific formatting like `\...\` for French, `[...]` for German, etc.):
- `EN`, `FR`: now supports multiple cross-sections pronunciations (like ones from Middle English combined to ones from Old English sections, for instance on English data)
- `FR`: pronunciations outside the French section are no more taken into account (like using values from Gaulois or other locale sections, that was incorrect)
- `PT`: a lot more pronunciations are correctly found now
- …
=> Pronunciations refactoring

tests/test_ca.py, tests/test_de.py, tests/test_el.py, tests/test_en.py, tests/test_es.py, tests/test_fr.py, tests/test_it.py, tests/test_pt.py, tests/test_ru.py, tests/test_sv.py, wikidict/convert.py, wikidict/get_word.py, wikidict/lang/__init__.py, wikidict/lang/ca/__init__.py, wikidict/lang/de/__init__.py, wikidict/lang/defaults.py, wikidict/lang/el/__init__.py, wikidict/lang/en/__init__.py, wikidict/lang/es/__init__.py, wikidict/lang/fr/__init__.py, wikidict/lang/it/__init__.py, wikidict/lang/pt/__init__.py, wikidict/lang/ru/__init__.py, wikidict/lang/sv/__init__.py, wikidict/render.py, wikidict/stubs.py, wikidict/utils.py
Same work as done for pronunciations in #1377.
- fixes #993 
- multiple genders support for all locales
- moved pronunciations, and genders, tests into doctests
Maybe the new code, and the one for pronunciations, could be refactored more to automatically get rid of duplicates (and still keeping the retrieval order).
=> Genders refactoring

tests/test_es.py, wikidict/utils.py
Fixes #584.
It's fixed for all devices, and all locales.
Maybe is it too broad for such a fix? I'm fine with that, as soon as you are too @lasconic.
Bonus point: `--check-word` passes just fine with such changes.
=> Arabic and Persian scripts not rendered in italic

tests/test_fr.py, wikidict/lang/fr/__init__.py
=> [FR] support "diaéthique" template

wikidict/lang/fr/template_handlers.py, wikidict/utils.py
Fixes #1478 
If the param of a template will be enclosed by the template code between [[]] then we need to call the new function `process_special_pipe_template`. So far, only cf is known to do this.
=> fix #1478: Fix '!' template handling

wikidict/lang/fr/template_handlers.py
=> fix #1477: [FR] Support 'T' template

wikidict/user_functions.py
Fixes #1504
It seems quite fragile, but we only output ourselves a `=` in `small_caps()`. Do you have a better idea @lasconic?
=> Avoid splitting blindly in `extract_keywords_from()`

wikidict/lang/fr/template_handlers.py
=> [FR] Ignore the "cf" template when pointing to the current Wiki page

tests/test_ca.py, wikidict/lang/ca/__init__.py
=> [CA] Support multiple arguments in "q" template

tests/test_ca.py, wikidict/lang/ca/__init__.py
=> [CA] Support "AFI" template

wikidict/lang/pt/__init__.py
We could improve the support, notably:
- Remove the ugly hack to add a unbreakable space in French.
- Some composed langs should not be `title()`ed, like "Tártaro Da Crimeia" -> "Tártaro da Crimeia"
But let's keep it simple for now, and see if something breaks.
Fixes #1611
=> [PT] Reconsider "trad" support

requirements.txt, wikidict/utils.py
Fixes #1678
The improvement is light, but it removes any cache issues.
This also improves a little bit the overall process because we get rid of a list -> tuple conversion, and we removed a function call for each word.
See https://github.com/BoboTiG/ebook-reader-dict/issues/1678#issuecomment-1403361013 for numbers.
=> fix #1678: Fix template transformation cache issues

scripts/fr-racines-arabes.py, wikidict/lang/fr/__init__.py, wikidict/lang/fr/ar_pronunciation.py, wikidict/lang/fr/ar_translit.py, wikidict/lang/fr/arabiser.py, wikidict/lang/fr/racines_arabes.py
=> fix #1411: [FR] Add support for the 'ar-terme' template

tests/test_2_render.py, tests/test_4_check_word.py, tests/test_de.py, wikidict/check_word.py, wikidict/hiero_utils.py, wikidict/lang/de/__init__.py, wikidict/lang/de/template_handlers.py, wikidict/lang/fr/arabiser.py, wikidict/lang/ru/__init__.py, wikidict/render.py
=> fix #1732: [DE] Support "Ref-behindthename" template, and others

wikidict/convert.py
`pyglossary.glossary_v2` module is added in [PyGlossary 4.6.0](https://github.com/ilius/pyglossary/releases/tag/4.6.0).
[A quick overview of differences in README](https://github.com/ilius/pyglossary#using-pyglossary-as-a-python-library).
`pyglossary.glossary` (and `from pyglossary import Glossary`) is kept for compatibility (not deprecated).
=> Switch to pyglossary.glossary_v2

tests/data/ro/cânta.wiki, tests/test_ro.py, wikidict/lang/ro/__init__.py, wikidict/render.py
Related to  #1771.
I simply added a `assert 0, template` in `last_template_handler()` and added missing templates. I should have missed something because only 3 templates were found :)
Anyway, the number of rendered words went from `76,202` to `94,209` (out of `94,681`) 🍾 
I found missing verbs that are using subsections like https://ro.wiktionary.org/wiki/avea and https://ro.wiktionary.org/wiki/fi, will see later.
Also, I'm working on variants support right now.
=> [RO] Fix verb support + handle all templates found

scripts/scripts_utils.py, wikidict/lang/fr/__init__.py, wikidict/lang/fr/arabiser.py
=> fix #1844: [FR] Fix support for 'ar-cf' template

wikidict/get_word.py
I wanted to have a look at https://github.com/BoboTiG/ebook-reader-dict/actions/runs/7312869332/job/19923855661, but logs are no more available.
I'm trying this approach then: setting job summaries. I do not know if they will survive the logs yet, but anyway it seems cool.
=> ci(random-daily-word): Set the job summary with words

docs/de/README.md
With appropriate borrowings from the French docs that are not present in the English:
- pour être parfaitement lisibles — und lässt sich damit fehlerfrei anzeigen
- images vectorielles — Vektorgrafiken (instead of “SVG”)
Reformulate the disambiguation feature description in terms of “lemma” — less cumbersome wording.
=> [DE] Translate docs

tests/test_ca.py, wikidict/lang/ca/__init__.py
=> [CA] Fix support for "etim-s" template

scripts/en-langs.py, wikidict/lang/en/langs.py, wikidict/lang/en/template_handlers.py
I'm not sure this is a nice patch, but it fixes:
```python
>>> render_foreign_derivation("learned borrowing", ["en", "LL.", "trapezium"], defaultdict(str, {"notext":"1"}))
Expected:
'Late Latin <i>trapezium</i>'
Got:
'<i>trapezium</i>'
```
=> [EN] Fix missing lang aliases

tests/test_en.py, wikidict/lang/en/__init__.py, wikidict/lang/en/template_handlers.py
About the `ISO 639` template: https://en.wiktionary.org/wiki/Template:ISO_639/documentation
It is partially supported: it won't work for when the code is a number (yet?).
=> [EN] Support translingual section + partial "ISO 639" template

tests/conftest.py, wikidict/parse.py
The profiled code is:
```python
from time import monotonic
from pathlib import Path
from wikidict.parse import xml_iter_parse, xml_parse_element
file = Path("data/no/pages-20240901.xml")
start = monotonic()
for element in xml_iter_parse(file):
xml_parse_element(element, "no")
end = monotonic()
print(end - start, "sec")
```
On my machine, parsing I got those values:
- Before: 3.10 sec
- After : 1.10 sec
---
I also run the "Update data" workflow to check for any regression. It appears, the new parser find more words, and it blazing fast :champagne: 
New *rendered* words:
- French: +1
- German: +1,296
- Greek: +1
- Italian: +2
- Russian: +1
Parsing times:
- all: at least divided by 2
- French: 3m27s -> 1m25s
- English: 5m20s -> 2m4s
---
It might be possible to improve even more, of course! …
=> feat: optimized XML parser

wikidict/check_word.py, wikidict/lang/defaults.py, wikidict/render.py
Missing templates are now printed at the end of the process, sorted by the total number of occurrences, and with 3 examples. It will ease prioritizing our work, eventually.
Example of output from the Greek dictionary:
Missing 'λείπει η ετυμολογία' template support (45,707 times), example in: "Αϊδωνιά", "Αϊδώνα", "Αϊντίνι"
Missing 'πρόσφ' template support (12,971 times), example in: "-δικείο", "-μάλλης", "-πλευρος"
Missing 'μτφδ' template support (4,352 times), example in: "-γόνος", "-κέφαλος", "-καλλιέργεια"
Missing 'δαν' template support (3,808 times), example in: "-άδα", "-άρω", "-έζος"
Missing 'βλ' template support (3,581 times), example in: "'γγίζω", "-έλαιο", "-ήδικος"
(...)
Unhandled templates count: 117
=> feat: improve how missing templates are reported

wikidict/convert.py
If PyGlossary (since 5.0) failed to convert, it will raise exception (of custom type `Error`).
So no need for `assert`.
=> Minor cleanup in convert

tests/conftest.py, tests/test_2_render.py, wikidict/check_word.py, wikidict/check_words.py, wikidict/get_word.py, wikidict/lang/ca/__init__.py, wikidict/lang/da/__init__.py, wikidict/lang/de/__init__.py, wikidict/lang/defaults.py, wikidict/lang/el/__init__.py, wikidict/lang/en/__init__.py, wikidict/lang/eo/__init__.py, wikidict/lang/es/__init__.py, wikidict/lang/fr/__init__.py, wikidict/lang/it/__init__.py, wikidict/lang/no/__init__.py, wikidict/lang/pt/__init__.py, wikidict/lang/ro/__init__.py, wikidict/lang/ru/__init__.py, wikidict/lang/sv/__init__.py, wikidict/render.py, wikidict/utils.py
Definitively fixes #1054, and simplify the thinking process while adding more explicit code.
It seems a lot of code, maybe that's not the best approach, but at least it feels more proper & explicit: I added the `missed_templates` keyword-argument from top calls until the lowest function. It will work either with a simple list (like when used from `--get-word`, or `--check-word`), a shared `multiprocessing` object (like in `--render`), and it does not break other code since it is `None` by default.
No more global variables, and I tested with all `multiprocessing` start methods (fork, forkserver, and spawn): they all work.
Bonus points:
- `--check-words` now reports missed templates
- no more side-effects in tests: each run has its own `missed_template` value (as seen in `test_2_render.py` …
=> fix: remove problematic process-shared global variables

wikidict/lang/da/__init__.py, wikidict/lang/en/__init__.py, wikidict/lang/sv/__init__.py, wikidict/parse.py, wikidict/render.py
For several locales it is more accurate to use a regexp matcher:
- CA,DA,EL,EN,EO,IT,NO,PT,SV: more accurate parsing (remove false positives or no change)
While for others, a simple check is better because it is either more accurate, or simply impossible to rely on the former.
Fixes #2374.
=> feat(experimental): change the way we check for head sections

.gitignore, log-analyzer.py, requirements.txt, tests/test_1_parse.py, tests/test_ca.py, wikidict/__main__.py, wikidict/constants.py, wikidict/context.py, wikidict/lang/__init__.py, wikidict/lang/ca/__init__.py, wikidict/lang/da/__init__.py, wikidict/lang/de/__init__.py, wikidict/lang/defaults.py, wikidict/lang/el/__init__.py, wikidict/lang/en/__init__.py, wikidict/lang/eo/__init__.py, wikidict/lang/es/__init__.py, wikidict/lang/fr/__init__.py, wikidict/lang/fr/template_overrides.py, wikidict/lang/it/__init__.py, wikidict/lang/no/__init__.py, wikidict/lang/pt/__init__.py, wikidict/lang/ro/__init__.py, wikidict/lang/ru/__init__.py, wikidict/lang/sv/__init__.py, wikidict/parse.py, wikidict/render.py, wikidict/utils.py
Closes #2500.
Closes #2520.
Related to #2528.
Summup:
- tables support: ✔️
- hieroglyphs support: ✔️
- chemical/math formulas: ✔️
- thread-safety: ✔️
- pronunciations/genders: ✔️
- variants: ✔️
- reverse variants: ✔️
Locales support:
1. CA: ✔️
1. DA: ✔️ 
1. DE: ✔️
1. EL: ✔️
1. EN: ✔️ (the `transclude` module is problematic, it's about 6k impacted words, we can move without these missing definitions for a start)
1. EO: ✔️
1. ES: ✔️
1. FR: ✔️ 
1. IT: ✔️
1. NO: ✔️
1. PT: ✔️
1. RO: ✔️
1. RU: ✔️
1. SV: ✔️
1. ZH: ✔️ (`transclude` support needed too, plus module clean-up in database, for later)
---
Notes:
1. About numbers, `--render` can be faster or equal for most locales, and at most double for big ones like FR/EN (from 9 minutes to 18, that's really not an issue). Interestingly, DE with …
=> feat: use a Lua interpreter for modules & templates rendering
