reader-dict/monolingual

.github/workflows/auto-updates.yml
README.md
html/scripts/user_functions.html
scripts/lang/__init__.py
scripts/lang/es.py
scripts/user_functions.py
tests/data/es/-acho.wiki
tests/data/es/Mús..wiki
tests/data/es/cartel.wiki
tests/data/es/comer.wiki
tests/data/es/es decir.wiki
tests/data/es/extenuado.wiki
tests/data/es/futuro.wiki
tests/data/es/gracias.wiki
tests/data/es/hasta.wiki
tests/data/es/los.wiki
tests/data/es/también.wiki
tests/data/es/tres.wiki
tests/data/es/uni-.wiki
tests/data/es/zzz.wiki
tests/test_es.py
update-tags.sh

Introduced a new user function for the occasion: `coord()`.

New locale: Spanish

---

scripts/lang/ca.py
tests/test_ca.py

fix #178: [CA] Handle the 'etim-s' template

---

scripts/get.py
scripts/lang/__init__.py
scripts/lang/ca/__init__.py
tests/test_ca.py

fix #136: [CA] Add etymology

---

scripts/lang/ca/__init__.py
tests/data/ca/PMF.wiki
tests/data/ca/el.wiki

Ex: https://ca.wiktionary.org/wiki/m%C3%A8tode

[CA] Improve the pronunciation regex (closes #188)

---

scripts/get.py

Other locales have already defined sections and it would slow the whole proces for those.

Only add a fake etymology section for CA (related to #136)

---

scripts/lang/ca/__init__.py
tests/test_ca.py

fix #187: [CA] Fix handling of the 'etim-lang' template

---

scripts/constants.py
scripts/convert.py
scripts/get.py
scripts/lang/fr/__init__.py
scripts/stubs.py
tests/data/fr/colligeait.wiki
tests/data/fr/colliger.wiki
tests/test_0_get.py
tests/test_fr.py

fix #167: [FR] Redirect conjuged verbs to their infinitive form

---

scripts/constants.py
scripts/convert.py

fix #143: Investigate signature display on Kobo 4.24.15676

---

scripts/convert.py

Normalize variants (#167)

---

scripts/convert.py
scripts/get.py
scripts/stubs.py
tests/test_fr.py

fix #215 : [FR] Support multiple variants

---

scripts/convert.py
scripts/get.py
scripts/stubs.py
scripts/utils.py
tests/test_0_get.py
tests/test_ca.py
tests/test_en.py
tests/test_es.py
tests/test_fr.py
tests/test_pt.py
tests/test_sv.py

Support multiple pronunciations

---

scripts/convert.py

fix tests coverage

---

scripts/lang/fr/__init__.py
tests/test_fr.py

fix #229: [FR] Support W template

---

scripts/lang/defaults.py
scripts/lang/fr/__init__.py
scripts/user_functions.py
tests/test_fr.py

fix #234: [FR] Handle 'domain templates' with more than 2 parts

---

scripts/lang/defaults.py
tests/test_fr.py

fix #231: [FR] Support Lang template

---

scripts/lang/fr/__init__.py

fix #238: [FR] handle Polytonique template (capital P...)

---

scripts/lang/fr/__init__.py
tests/test_fr.py

fix #236: [FR] Handle graphie Template

---

scripts/convert.py
scripts/get.py
scripts/stubs.py
tests/test_0_get.py
tests/test_fr.py

fix #237: [FR] Sub sub list not handled correctly

---

scripts/lang/fr/__init__.py

fix #241: handle 'déverbal sans suffixe' template

---

scripts/lang/fr/__init__.py

Ex: https://fr.wiktionary.org/wiki/natchez

[FR] Handle the 'phon' template (closes #255)

---

scripts/lang/fr/__init__.py

fix #258: [FR] Handle 'syncope' et 'parataxe'

---

scripts/lang/__init__.py
scripts/lang/defaults.py
scripts/lang/fr/__init__.py
scripts/utils.py

- Stop early the template processing if it should be ignored.
It will also unshadow some french templates that should be totally ignored (like "lien web").

Simplify transform()

---

scripts/lang/fr/__init__.py
tests/test_fr.py

fix #254: [FR] Handle 'Unité' template (capital U...)

---

scripts/lang/fr/__init__.py

fix #250: [FR] handle 'supplétion' template

---

scripts/lang/fr/__init__.py
tests/test_fr.py

fix #268: [FR] Handle 'dénominal de' and 'déverbial de' templates

---

.github/workflows/auto-updates.yml
scripts/utils.py

Do you think it is worth flooding the console? :)

Ease tracking of unsupported templates

---

scripts/lang/fr/__init__.py

fix #270: [FR] Handle 'déglutination' Template

---

scripts/lang/fr/__init__.py
tests/test_fr.py

fix #274: [FR] handle détroit template

---

scripts/lang/fr/__init__.py
tests/test_fr.py

fix #277: [FR] Handle 'Variante de' (Capital V...)

---

scripts/lang/fr/__init__.py

Ex: https://fr.wiktionary.org/wiki/liseuse

[FR] Support the 'équiv-pour' template (closes #280)

---

scripts/lang/fr/__init__.py

fix #283: [FR] Handle 'volley' template

---

scripts/lang/fr/__init__.py
tests/test_fr.py

fix #279: [FR] Handle 'diminutif' template

---

scripts/lang/fr/__init__.py

[FR] Fix 'acronyme' handling

---

scripts/lang/fr/__init__.py

Ex: https://fr.wiktionary.org/wiki/BIM

[FR] Fix 'date' handling with question mark (fixes #286)

---

scripts/lang/fr/__init__.py

fix #289: [FR] Handle 'reverlanisation' template

---

scripts/lang/fr/__init__.py

fix #272: [FR] Handle 'LienRouge' template

---

scripts/lang/fr/__init__.py
tests/test_fr.py

fix #295: [FR] Handle 'trad-' template

---

scripts/lang/fr/__init__.py
tests/test_fr.py

fix #293: [FR] handle 'cours d'eau' template

---

scripts/lang/fr/__init__.py
tests/test_fr.py

fix #300: [FR] Handle 'incise' template

---

scripts/lang/fr/__init__.py

fix #299: [FR] Handle 'formule chimique' template

---

scripts/utils.py

Log only once a missing template

---

scripts/lang/fr/__init__.py

- Sorted doctests.
- Sorted conditions.
- Always use `extract_keywords_from()`.
- Removed useless comments.

[FR] Clean-up last_template_handler()

---

scripts/lang/fr/__init__.py

fix #307: [FR] Handle the 'argot' template

---

scripts/lang/fr/__init__.py

fix #312: [FR] Handle the 'dérision' template

---

scripts/lang/fr/__init__.py

Ex: https://fr.wiktionary.org/wiki/Elbeuf

[FR] Ignore the 'Ouvrage' template (closes #313)

---

scripts/lang/fr/__init__.py

fix #311: [FR] Handle the 'verlan' template

---

scripts/lang/fr/__init__.py

fix #310: [FR] Support the 'la-verb' template

---

scripts/lang/fr/__init__.py
tests/test_fr.py

fix #324: [FR] Support 'wd' template

---

scripts/lang/fr/__init__.py
tests/test_fr.py

- [] Fixes #
- [] Tests added/updated.

Miscellaneous fixes related to issue #257

---

scripts/lang/fr/__init__.py

fix #327: [FR] Handle 'Suisse' template

---

scripts/lang/en/langs.py

fix #330: [EN] missing afa language code

---

scripts/lang/fr/__init__.py

fix #326: [FR] Incorrect 'composé de' template with multiple parts

---

scripts/lang/fr/__init__.py

fix #335: [FR] Support 'locutions latines' template

---

scripts/lang/fr/__init__.py
scripts/user_functions.py

fix #337: [FR] Incorrect rendering of cf with more than 2 parts

---

scripts/lang/fr/__init__.py

fix #339: [FR] support 'Légifrance' template

---

scripts/lang/fr/__init__.py
tests/test_fr.py

fix #341: [FR] Support 'mn-lien' template

---

scripts/lang/en/__init__.py

- Sorted doctests.
- Sorted conditions.
- Always use `extract_keywords_from()`.
- Removed useless comments.

[EN] Clean-up last_template_handler()

---

scripts/lang/fr/__init__.py
tests/test_fr.py

fix #367: [FR] Support 'SIC' template

---

scripts/utils.py

Ex: https://fr.wiktionary.org/wiki/apr._J.-C.
Ex: https://fr.wiktionary.org/wiki/De_Witte

Add support for several magic words (closes #356)

---

scripts/lang/en/__init__.py
tests/test_en.py

fix #353: [EN] Handle the 'doublet' template

---

scripts/utils.py

Ex: https://en.wiktionary.org/wiki/Iraq

Clean-up <<foo/bar>> wikicode (closes #349)

---

scripts/lang/en/__init__.py
tests/test_en.py

fix #380: handle q template, improve qualifier and qual templates

---

scripts/lang/en/__init__.py

fix #385: [EN] ignore root template

---

scripts/lang/en/__init__.py

fix #352: Handle prefix, suffix, confix, compound, blend templates

---

scripts/utils.py

fix #387: [EN] Fix <ref/> filtering

---

.github/workflows/tests.yml
scripts/lang/en/__init__.py
scripts/user_functions.py

fix misc. errors for english

---

scripts/lang/en/__init__.py

fix #391: [EN] Support affix/af template

---

scripts/lang/en/__init__.py

fix #392: [EN] Support noncog/noncognate template

---

scripts/lang/en/__init__.py

fix #395: [EN] Ignore multiple templates for english

---

scripts/lang/en/__init__.py
tests/test_en.py

fix #402: [EN] Handle init of / initialism of template

---

scripts/lang/en/__init__.py

fix #405: [EN] support '&lit' template

---

html/scripts/user_functions.html
scripts/get.py
scripts/user_functions.py
scripts/utils.py
tests/test_ca.py
tests/test_en.py
tests/test_es.py
tests/test_fr.py
tests/test_pt.py
tests/test_sv.py

It will be useful for the upcoming work on the 'Citation' handling.

Split the work done by clean into 2 specific functions

---

scripts/lang/en/__init__.py

fix #410: [EN] Support 'given name' template

---

scripts/lang/en/__init__.py

fix #413: [EN] Support template aliases: pre, suf, com, blend of

---

scripts/lang/fr/__init__.py

Ex: https://fr.wiktionary.org/wiki/Mortes-Fronti%C3%A8res

[FR] Support the 'Citation' template (closes #365)

---

scripts/lang/en/__init__.py
scripts/lang/en/form_of.py
tests/test_en.py

fix #415: [EN] Support all 'form-of' templates

---

scripts/lang/en/__init__.py

fix #422: [EN] add shortcuts of supported templates

---

scripts/lang/en/__init__.py

fix #420: [EN] bad render of 'blend of'

---

scripts/lang/en/__init__.py
tests/test_en.py

fix #425: [EN] Support used Foreign derivation templates

---

scripts/lang/en/__init__.py

fix #427: [EN] Support 'unk' template

---

scripts/lang/en/__init__.py

fix #429 #419 [EN] Support 'back-formation', 'coin/coinage' templates

---

scripts/lang/en/__init__.py

Ex: https://en.wiktionary.org/wiki/translation

[EN] Support '...' and 'nb...' templates (closes #431)

---

scripts/lang/en/__init__.py

fix #437: [EN] Support 'nuclide' and 'frac' templates

---

scripts/lang/en/__init__.py

fix #441: [EN] Crash on coin/coinage template

---

scripts/lang/en/__init__.py
tests/test_en.py

fix #438: [EN] Support 'Latn-def' template

---

scripts/lang/en/__init__.py

fix #439: [EN] Support all English form-of templates

---

scripts/lang/fr/__init__.py

Ex: https://fr.wiktionary.org/wiki/Martini

[FR] Support the 'nom-déposé' template (closes #450)

---

scripts/lang/fr/__init__.py

Ex: https://fr.wiktionary.org/w/index.php?title=Murois

[FR] Support 'note-gentilé' template (closes #449)

---

scripts/lang/fr/__init__.py

Ex: https://fr.wiktionary.org/wiki/d%C3%A9sinfantiliser

[FR] Support 'p-us' template (closes #451)

---

scripts/lang/fr/__init__.py
scripts/lang/fr/template_handlers.py
tests/test_fr.py

Issue #459: Start locale refactoring

---

scripts/lang/es/__init__.py
scripts/lang/es/template_handlers.py

Issue #459: refactor ES locale

---

README.md
check.sh
requirements.txt
setup.cfg
tests/test_main_download.py
wikidict/__init__.py
wikidict/__main__.py
wikidict/constants.py
wikidict/download.py

Project refactoring: download step (related to #458)

---

scripts/lang/fr/__init__.py
tests/test_fr.py

fix #457: [FR] Support 'x10' template

---

wikidict/__main__.py
wikidict/find_templates.py
wikidict/get_word.py
wikidict/parse.py
wikidict/render.py

start --parse and --render

---

wikidict/get_word.py

Ex: `python -m wikidict fr --get-word isabelle`

--get-word: Strip &thinsp; HTML character

---

wikidict/__main__.py
wikidict/parse.py

Also start the whole process when there is no argument.

--parse: Do not parse again if it was already done

---

wikidict/__main__.py
wikidict/convert.py

Implement convert step, add DF file support

---

wikidict/convert.py
wikidict/render.py

parallelize render

---

tests/test_ca.py
tests/test_en.py
tests/test_es.py
tests/test_fr.py
tests/test_pt.py
tests/test_sv.py

update locale tests to use the new wikidict package

---

scripts/lang/fr/__init__.py
scripts/lang/fr/arabiser.py

Fix #456: [FR] Handle ar-mot and ar-terme

---

.github/workflows/auto-updates.yml

Fix StarDict file creation

---

wikidict/lang/en/template_handlers.py

fix #448: [EN] Support 'historical given name' template

---

wikidict/utils.py

cf https://www.mediawiki.org/wiki/Help:Magic_words#Date_and_time

Fix CURRENTMONTH* magic words tests (fixes #498)

---

check.sh
requirements.txt
scripts/__main__.py
scripts/ca-langs.py
scripts/en-form-of.py
scripts/en-langs.py
scripts/en-places.py
scripts/es-langs.py
scripts/fr-domain-templates.py
scripts/fr-langs.py
scripts/pt-gramatica.py
scripts/pt-langs.py

fix #507: Add scripts to auto-update specific data

---

wikidict/lang/en/template_handlers.py

fix #513: [EN] Fix handling of the 'named-after' template

---

wikidict/lang/ca/__init__.py

Ex: https://ca.wiktionary.org/wiki/transmutaci%C3%B3

fix #521: [CA] Handle the 'trad' template

---

wikidict/__main__.py
wikidict/check_word.py

add first version of check_word

---

wikidict/check_word.py

For example, with "[FR] être", the number of errors went from 5 to 3.

--check-word: Check with all spaces removed

---

wikidict/lang/pt/__init__.py

Ex: https://pt.wiktionary.org/wiki/demiss%C3%A3o

fix #551: [PT] Better handling of the 'etimo' template

---

wikidict/lang/ca/__init__.py
wikidict/lang/defaults.py
wikidict/lang/en/template_handlers.py
wikidict/lang/fr/template_handlers.py
wikidict/utils.py

[FR] Fix handling of the 'composé de' template

---

wikidict/lang/en/template_handlers.py

fix #544: [EN] Improve handling of CDP 'place' template

---

wikidict/lang/es/template_handlers.py

fix #548: [ES] Fix handling of the 'etimología' template

---

wikidict/lang/fr/template_handlers.py

fix #559: [FR] Empty 'abréviation' should be around parenthesis

---

tests/test_4_check_word.py
wikidict/check_word.py

fix #549: [ES] --check-word is not yet compatible with the locale

---

wikidict/lang/fr/template_handlers.py

fix #558: [FR] Better handling of the 'étyl' template

---

tests/test_fr.py
wikidict/lang/fr/__init__.py

fix #573: [FR] tweak handling of 'nom w pc'

---

tests/test_1_parse.py
wikidict/parse.py

fix #575: Optimize parse step by filtering foreign words out

---

wikidict/lang/fr/__init__.py
wikidict/lang/fr/template_handlers.py

fix #581: [FR] Better suport of the 'mot-valise' template

---

tests/test_es.py
wikidict/lang/es/__init__.py

fix #580: [ES] Improve handling of 'sustantivo de verbo' template

---

tests/test_es.py
wikidict/lang/es/__init__.py

fix #586: [ES] Better support for 'adjetivo de sustantivo'

---

wikidict/lang/es/template_handlers.py

fix #579: [ES] Improve handling of 'etimología' template

---

wikidict/lang/pt/__init__.py

Ex: https://pt.wiktionary.org/wiki/fim

fix #596: [PT] Add support for country templates

---

wikidict/lang/__init__.py

fix #588: [ES] [[Categoría]] shouldn't be printed

---

tests/test_es.py
wikidict/lang/es/__init__.py
wikidict/lang/es/template_handlers.py

fix #589: [ES] Better support of 'superlativo'

---

wikidict/lang/es/__init__.py

fix #591: [ES] Handle 'etim' template

---

wikidict/lang/es/template_handlers.py

fix #593: [ES] Support {{etimología|incierta}}

---

wikidict/lang/es/__init__.py

fix #590: [ES] Ignore 'forma verbo' template

---

wikidict/lang/fr/template_handlers.py

fix #620: [FR] Improve handling of 'siècle' template

---

wikidict/lang/fr/template_handlers.py

fix #624: [FR] Improve 'Composé de' template for empty param

---

wikidict/lang/fr/template_handlers.py

fix #627: [FR] Change dash in 'siècle' template

---

wikidict/lang/fr/__init__.py
wikidict/lang/fr/template_handlers.py

fix #626: [FR] improve support of 'aphérèse' template

---

wikidict/lang/fr/__init__.py
wikidict/utils.py

fix #630: [FR] mix of italic and bold and apostrophe

---

wikidict/lang/fr/template_handlers.py

fix #633: [FR] improve 'abréviation' template

---

wikidict/check_word.py

Optimize check-word when no etymology nor definitions

---

wikidict/lang/fr/langs.py

fix #642: [FR] Add missing 'latin archaïque' and other latins to langs

---

wikidict/lang/fr/__init__.py
wikidict/lang/fr/langs.py

fix #641: [FR] Add support for the 'substantivation de' template

---

.github/workflows/auto-update-data.yml
.github/workflows/auto-updates.yml
.github/workflows/quality.yml
.github/workflows/tests.yml
requirements.txt
tests/test_fr.py
wikidict/lang/fr/__init__.py
wikidict/lang/fr/template_handlers.py

[FR] Better support for 'ws' template

---

tests/test_fr.py
wikidict/lang/fr/__init__.py
wikidict/lang/fr/template_handlers.py

Ex: https://fr.wiktionary.org/wiki/Norv%C3%A8ge

fix #638: [FR] Better support for 'WP' template

---

wikidict/lang/en/template_handlers.py

fix #656: [EN] Handle empty parts of the 'suffix' template

---

wikidict/__main__.py
wikidict/convert.py
wikidict/gen_dict.py
wikidict/get_word.py

fix #666: Add --gen-dict command to create a dict from some words

---

wikidict/check_word.py

fix #669: [FR] check-word is too strict when removing anchors

---

wikidict/lang/fr/__init__.py

fix #670: [FR] Handle empty param in 'cf' template

---

wikidict/lang/fr/__init__.py
wikidict/lang/fr/template_handlers.py

fix #672: support doute parameter in 'siècle' template. Support 'litote' template

---

wikidict/lang/fr/template_handlers.py

fix #675: [FR] review 'composé de' with 3 terms

---

wikidict/check_word.py
wikidict/lang/fr/__init__.py

fix #679: [FR] Support 'R:TLFi' template

---

wikidict/check_word.py
wikidict/lang/fr/__init__.py

Reverts BoboTiG/ebook-reader-dict#688
See #679

Revert "fix #679: [FR] Support 'R:TLFi' template"

---

tests/test_4_check_word.py
tests/test_fr.py
wikidict/check_word.py
wikidict/lang/fr/__init__.py
wikidict/lang/fr/template_handlers.py

I ran check-word on 50k words, got a couple hundreds errors.
So I fixed the obvious ones here and created issues for the others.
---------------------- >8 ------------------------
Requesting a pull to BoboTiG:master from lasconic:misc-fixes-2
Write a message for this pull request. The first block
of text is the title and the rest is the description.
Changes:
b86f773 (lasconic, 10 seconds ago)
[FR] misc. improvements thanks to check-word
9198eb5 (lasconic, 69 seconds ago)
[FR] Improve check-word

Improve check-word for french and misc. fixes.

---

wikidict/lang/fr/__init__.py
wikidict/lang/fr/template_handlers.py

fix #694: [FR] Support m option in 'antonomase' template

---

tests/test_fr.py
wikidict/lang/fr/__init__.py
wikidict/lang/fr/template_handlers.py

fix #701: [FR] Support options of 'variante orthographique de' template

---

tests/test_4_check_word.py
wikidict/check_word.py
wikidict/lang/fr/__init__.py

fix #704: [FR] check-word should ignore 'sur Wikispecies' text

---

wikidict/lang/fr/__init__.py
wikidict/lang/fr/template_handlers.py

Also fix wikipédia accent in WP template and lexique template containing = options

fix #706: [FR] Improve 'siècle' template with punctuation

---

wikidict/check_word.py

fix #708: [FR] check-word crash on 'wsp' template

---

wikidict/lang/fr/__init__.py
wikidict/lang/fr/template_handlers.py

Also better support for 'w' template, 'marque déposée', etc...

fix #709: [FR] Handle 'ar-ab' template

---

wikidict/lang/fr/__init__.py

fix #713: [FR] crash on 'ar' template

---

tests/test_4_check_word.py
wikidict/check_word.py
wikidict/lang/fr/__init__.py

fix #712: [FR] handle 'attention' template consistenly and support in check-word

---

wikidict/lang/fr/__init__.py

misc. fixes

---

.github/workflows/auto-updates.yml
.github/workflows/tests.yml
tests/test_4_check_word.py
wikidict/check_word.py
wikidict/utils.py

Also fix a couple of errors with <math> and improve debug

fix #716: Support <chem> extension

---

wikidict/utils.py

Ex: https://fr.wiktionary.org/wiki/gcr

fix #723: Error in handling template directly surrounded by link

---

wikidict/lang/fr/__init__.py
wikidict/lang/fr/template_handlers.py

fix #718: [FR] Improve 'sigle' template

---

tests/test_4_check_word.py
wikidict/check_word.py
wikidict/lang/fr/__init__.py
wikidict/lang/fr/template_handlers.py

misc. fixes and more test coverage

---

wikidict/lang/en/template_handlers.py

fix #731: [EN] Fix a crash when 'coinage' has no simple arguments

---

tests/test_fr.py
wikidict/lang/fr/__init__.py

fix #727: [FR] Support 'registre' template

---

tests/test_fr.py
wikidict/lang/fr/__init__.py
wikidict/user_functions.py

- The `nom w pc` template removed the use of small-caps for the last name.
- `person()` now handles correctly last name only usage.
---

[FR] Rework output of the person() user function

---

wikidict/lang/en/template_handlers.py

fix #760: [EN] Fix support for etyl with a single arg

---

wikidict/lang/fr/__init__.py

fix #758: [FR] Ignore the 'lire en ligne' template

---

wikidict/lang/en/template_handlers.py

fix #761: [EN] Improve 'affix' template support

---

tests/data/es/entrada.wiki
tests/test_es.py
wikidict/lang/__init__.py
wikidict/lang/es/__init__.py
wikidict/render.py

fix #73: [ES] Take into account sublists

---

wikidict/lang/ca/__init__.py

fix #659: [CA] Handle the 'pos' argument of the 'terme' template

---

wikidict/lang/es/__init__.py

fix #780: [ES] ignore 'catafijo' template

---

wikidict/lang/es/template_handlers.py

fix #776: [ES] Support 'adjetivo de verbo'

---

wikidict/lang/es/__init__.py
wikidict/lang/es/template_handlers.py

fix #777: [ES] Better support of 'etim' template

---

wikidict/lang/es/template_handlers.py

fix #779: [ES] Handle the 'num' argument of the 'l+' template

---

wikidict/lang/es/template_handlers.py

fix crash in etimologia with empty term

---

wikidict/render.py

fix #790: [ES] Missing definition

---

wikidict/lang/es/template_handlers.py

fix #799: [ES] better support for 'etimologia|confijo'

---

wikidict/lang/es/template_handlers.py

fix #801: [ES] fix support for 'etim' template

---

tests/test_fr.py
wikidict/lang/fr/__init__.py

fix #788: [FR] Support the 'ISBN' template

---

wikidict/lang/fr/__init__.py

fix #787: [FR] Ignore the 'article' template

---

tests/test_es.py
wikidict/lang/es/__init__.py

fix #805: [ES] formatnum should use space for thousand separator

---

tests/test_es.py
wikidict/lang/es/__init__.py

fix #798: [ES] Better support of 'gentilicio' template

---

wikidict/lang/es/__init__.py

fix #815: [ES] ignore 'marcar sin referencias' template

---

tests/test_es.py
wikidict/lang/es/template_handlers.py

fix #808: [ES] Improve 'etimologia/sufijo' and others

---

wikidict/lang/es/template_handlers.py

fix #809: [ES] Support 'adverbio de sustantivo' template

---

wikidict/lang/es/template_handlers.py

fix #810: [ES] support 'hipocorístico' template

---

wikidict/lang/es/template_handlers.py

fix #811: [ES] Support 'aumentativo' template

---

wikidict/lang/es/__init__.py
wikidict/lang/es/template_handlers.py

fix #814: [ES] better support of 'gentilicio2' template

---

wikidict/lang/es/template_handlers.py

fix #831: [ES] Support 'comparativo' template

---

wikidict/lang/es/template_handlers.py

fix #833: [ES] Support 'forma' template

---

tests/data/it/debolmente.wiki
tests/test_it.py
wikidict/lang/__init__.py
wikidict/lang/it/__init__.py
wikidict/render.py

[IT] Initial implementation

---

.github/workflows/auto-updates.yml
README.md
tests/data/no/konsentrasjon.wiki
tests/test_no.py
wikidict/lang/__init__.py
wikidict/lang/no/__init__.py
wikidict/render.py

First implementation.
Closes #754.

New locale: norsk [NO]

---

wikidict/lang/en/__init__.py

fix #846: [EN] Ignore the 'PIE word' template

---

wikidict/lang/en/__init__.py
wikidict/lang/en/template_handlers.py

fix #845: [EN] Handle 'ambitransitive' argument of 'lb' template

---

wikidict/render.py

--render: Apply subsection filtering

---

wikidict/find_templates.py
wikidict/render.py

Also improve sligthly the processing be computing only once sections title.

--render: Replace the filtering at the good location

---

tests/test_4_check_word.py
tests/test_es.py
wikidict/check_word.py
wikidict/lang/en/__init__.py
wikidict/lang/es/__init__.py
wikidict/lang/es/template_handlers.py
wikidict/lang/fr/__init__.py

Also improve test coverage.
Improve a couple of other ES templates

fix #834: [ES] Support 'color' template

---

tests/test_3_convert.py
tests/test_4_check_word.py
tests/test_ca.py
tests/test_fr.py
tests/test_it.py
tests/test_no.py
tests/test_pt.py
tests/test_sv.py
wikidict/constants.py
wikidict/convert.py
wikidict/get_word.py
wikidict/lang/__init__.py
wikidict/lang/ca/__init__.py
wikidict/lang/defaults.py
wikidict/lang/en/__init__.py
wikidict/lang/es/__init__.py
wikidict/lang/fr/__init__.py
wikidict/lang/it/__init__.py
wikidict/lang/pt/__init__.py
wikidict/render.py
wikidict/stubs.py
wikidict/utils.py

Thanks @atti84it for the catch!

Fix french genre -> gender

---

wikidict/lang/es/template_handlers.py

fix #835: [ES] Support 'preposición conjugada' template

---

wikidict/lang/es/template_handlers.py

fix #839: [ES] Support 'etimologia/regresiva' template

---

tests/test_4_check_word.py
wikidict/check_word.py
wikidict/lang/es/__init__.py
wikidict/lang/es/template_handlers.py
wikidict/render.py

fix #861: [ES] Support 'adjetivo de padecimiento'

---

wikidict/lang/es/template_handlers.py

fix #860: [ES] Support 'IPA' template

---

wikidict/__main__.py
wikidict/lang/es/__init__.py
wikidict/lang/es/template_handlers.py

fix #797: [ES] Support 'trad' template

---

tests/data/it/condividere.wiki
tests/data/it/lettore.wiki
tests/test_it.py
wikidict/lang/__init__.py
wikidict/lang/it/__init__.py

Many little things:
-support for "Term" template
-gender regex
-"debolmente" test updated
-added tests for "lettore" and "condividere"

[IT] "Term" template, gender regex, more tests

---

wikidict/lang/ca/__init__.py

fix #518: [CA] Handle the 'calc' template

---

wikidict/lang/en/template_handlers.py

fix #878: [EN] Better support of 'surname' template

---

tests/test_en.py
wikidict/lang/en/__init__.py
wikidict/lang/en/template_handlers.py

fix #877: [EN] better support for 'vern' template

---

tests/test_4_check_word.py
wikidict/check_word.py
wikidict/lang/en/template_handlers.py

fix #849: [EN] Handle 'otherforms=1' argument of 'nb...' template

---

wikidict/lang/es/__init__.py
wikidict/user_functions.py

Ex: https://es.wiktionary.org/wiki/adarme
Fixes #832.

fix #832: [ES] Support 'variantes' template

---

wikidict/utils.py

fix #884: Fix clean-up of link in single brackets

---

wikidict/utils.py

fix #886: Fix clean-up of external links

---

wikidict/utils.py

fix #888: Remove empty HTML tags

---

tests/test_fr.py
wikidict/utils.py

Fixes #894.
FYI @lasconic it simplifies a lot the templates parsing :)

fix #894: Handled nested templates having nested templates

---

wikidict/lang/fr/__init__.py
wikidict/lang/fr/regions.py
wikidict/lang/fr/template_handlers.py
wikidict/utils.py

fix #907: [FR] Support 'généralement pluriel' template, and more

---

wikidict/lang/fr/__init__.py
wikidict/lang/fr/template_handlers.py

fix #916: [FR] Review handling of 'réf?' template

---

tests/test_fr.py
wikidict/lang/fr/__init__.py
wikidict/lang/fr/template_handlers.py

fix #918: [FR] Fix handling of 'variante de' template

---

wikidict/lang/defaults.py

fix #923: Fix handling of 'w' template with data and parts set

---

wikidict/lang/fr/template_handlers.py

fix #926: [FR] Add support for the 'nom_langue' template

---

tests/test_4_check_word.py
wikidict/check_word.py

@lasconic what do you think about that? It could improve a lot our tasks.
Preview:

--check-word: Try to highlight where it starts to differ

---

wikidict/lang/defaults.py

fix #930: Fix handling of 'w' template when there are more than 2 parts

---

wikidict/lang/fr/__init__.py
wikidict/lang/fr/template_handlers.py

fix #932: [FR] Review handling of 'source?' template

---

wikidict/lang/__init__.py
wikidict/utils.py

fix #922: Fix cleanup of simple categories

---

wikidict/lang/fr/template_handlers.py

fix #921: [FR] Tweak handling of 'étylp' template

---

wikidict/lang/fr/template_handlers.py

fix #941: [FR] Support 'au masculin' template

---

wikidict/lang/fr/template_handlers.py

fix #945: Support 'date' argument of 'lien web' template

---

wikidict/lang/fr/__init__.py

fix #949: [FR] Review out of 'la-note-ij' template

---

wikidict/lang/fr/__init__.py

fix #952: [FR] Review out of 'note-gentilé' template

---

wikidict/lang/fr/__init__.py

fix #958: [FR] Review handling of 'ellipse' template

---

tests/test_fr.py
wikidict/lang/fr/__init__.py

fix #956: [FR] Add support for 'Mme' template

---

tests/test_fr.py
wikidict/lang/fr/__init__.py

fix #954: [FR] Add support for '1re' template

---

wikidict/lang/fr/__init__.py

fix #955: [FR] Add support for 'génit' template

---

wikidict/lang/fr/template_handlers.py

fix #959: [FR] Better handle 'étyl' template with empty word or tr

---

wikidict/lang/fr/__init__.py
wikidict/lang/fr/template_handlers.py

fix #951: [FR] Add support for 'laé' template

---

wikidict/utils.py

fix #691: Error in handling of links with [] in text

---

wikidict/lang/fr/__init__.py
wikidict/utils.py

fix #970: [FR] Support 'R:Larousse2vol1922' template

---

tests/test_4_check_words.py
wikidict/check_word.py
wikidict/check_words.py

fix #972: Parallelize --check-words to speed it up

---

.github/workflows/auto-updates.yml
README.md
update-tags.sh

Related to #977.
(+ autoformatting of YAML files)

Add Greek (el) locale to the docs and CI

---

wikidict/lang/__init__.py
wikidict/lang/el/__init__.py

fix #984: [EL] fix genre extraction for EL locale

---

wikidict/lang/it/__init__.py

Added support for 10 templates: Vd,Tabs,Quote,Taxon,Etim-link and more.

---

README.md
wikidict/lang/el/__init__.py

See https://github.com/BoboTiG/ebook-reader-dict/pull/986#issuecomment-873632437

Make the ignored template more inclusive

---

tests/test_it.py
wikidict/lang/it/__init__.py

fix #997: [IT] Fix handling of 'Vd' template

---

wikidict/lang/defaults.py
wikidict/render.py
wikidict/utils.py

It seems to work pretty well, WDYT @lasconic?
I put the code at one specific location where we know the template is missing. It is a good start.

New implementation to track missing templates

---

tests/test_fr.py
wikidict/lang/fr/__init__.py

fix #1006: [FR] Support 'phono' template

---

wikidict/lang/en/template_handlers.py

fix #1008: [EN] Fix 'bor' support with keyword-only arguments

---

tests/test_ca.py
wikidict/lang/ca/__init__.py

fix #1011: [CA] Support 'sinònim' template

---

wikidict/lang/fr/template_handlers.py

fix #1021: [FR] Support 'compos' template

---

tests/data/fr/Turgeon.wiki
tests/test_3_convert.py
tests/test_fr.py
wikidict/lang/fr/__init__.py

fix #1029: [FR] Keep 'nom de famille' sections

---

tests/test_fr.py
wikidict/lang/fr/__init__.py

fix #1028: [FR] No more ignoring 'plans d’eau' template

---

tests/test_fr.py
wikidict/lang/fr/__init__.py

fix #1026: [FR] Support 'souligner' template

---

tests/test_fr.py
wikidict/lang/fr/__init__.py

fix #1034: [FR] Handle 'pluriel' template

---

wikidict/lang/fr/__init__.py
wikidict/utils.py

fix #1036: [FR] Support 'R:Littré' template

---

tests/conftest.py
tests/data/en/42.html
tests/data/en/42.wiki
tests/data/es/buena.html
tests/data/es/buena.wiki
tests/data/fr/42.html
tests/data/fr/base.html
tests/data/fr/bath.html
tests/data/fr/éperon.html
tests/test_4_check_word.py
wikidict/check_word.py

Also reworked how tests are run for `--check-word`, it should be easier to maintain and apply future changes.
FTR, running:
$ python -m pytest tests/test_4_check_word.py --no-cov
went down from 25.99 sec to 2.33 sec!

--check-word: Rework tests to not require internet connection

---

wikidict/render.py

fix #1054: Cannot run tests on macOS

---

wikidict/user_functions.py

fix #1035: Improve handling of complex chimy symbols

---

wikidict/lang/fr/__init__.py
wikidict/utils.py

fix #1053: Support {{!}} magic template

---

tests/data/fr/-eresse.wiki
tests/test_fr.py
wikidict/lang/fr/__init__.py
wikidict/lang/fr/template_handlers.py
wikidict/render.py
wikidict/utils.py

fix #1024: [FR] Render wikitables in etymology

---

tests/data/ca/hivernacle.wiki
tests/test_ca.py
wikidict/lang/ca/__init__.py

fix #1090: [CA] Ignore 'ex-cit' template

---

wikidict/lang/ca/__init__.py

Fix #1094: [CA] Support 'term' template alias

---

tests/test_fr.py
wikidict/lang/fr/__init__.py
wikidict/render.py

Fix #663: [FR] Handling similar plurals and proper nouns

---

tests/data/fr/tests-definitions.wiki
tests/test_2_render.py
tests/test_3_convert.py
wikidict/lang/fr/__init__.py
wikidict/render.py

[FR] Ignore 'exemple' template & skip empty sub-definitions

---

wikidict/utils.py

Fix #1049: Improve clean-up of external links with title

---

wikidict/utils.py

Fix #407: Fix handling of words containing an equal sign

---

wikidict/lang/ca/__init__.py

Fix #1111: [CA] Support 'comp' support

---

wikidict/get_word.py
wikidict/lang/fr/__init__.py

Preliminary support only.
Fixes #785.

Fix #785: [FR] Support the 'Citation bloc' template

---

wikidict/utils.py

fix #1096 partially: Find a way to support custom Math expressions

---

wikidict/lang/fr/template_handlers.py

Fix #1132: [FR] Support '1e attestation' template

---

tests/data/de/CIA.wiki
tests/data/de/volley.wiki
tests/test_4_check_word.py
tests/test_de.py
wikidict/check_word.py
wikidict/lang/__init__.py
wikidict/lang/de/__init__.py
wikidict/render.py

New locale: DE

---

tests/test_5_gen_dict.py
wikidict/__main__.py
wikidict/convert.py
wikidict/gen_dict.py

fix #1185: --gen-dict should have an option to choose the format kobo/stardict

---

.github/workflows/auto-updates.yml
wikidict/convert.py
wikidict/lang/ca/__init__.py
wikidict/lang/de/__init__.py
wikidict/lang/el/__init__.py
wikidict/lang/en/__init__.py
wikidict/lang/es/__init__.py
wikidict/lang/fr/__init__.py
wikidict/lang/it/__init__.py
wikidict/lang/no/__init__.py
wikidict/lang/pt/__init__.py
wikidict/lang/sv/__init__.py

Compress StarDict 'dict-data.dict' to 'dict-data.dict.dz'

---

wikidict/convert.py

fix #1184: Incorrect br tag in output

---

wikidict/convert.py

Add website to StarDict metadata

---

tests/test_2_render.py
wikidict/__main__.py
wikidict/render.py

Defaults to the number of CPUs in the system.
Closes #1199.

--render: control the number of workers with --worker=N

---

wikidict/check_word.py
wikidict/lang/de/__init__.py
wikidict/lang/de/template_handlers.py

fix #1218: [DE] Support Üxx4 template

---

tests/test_3_convert.py
tests/test_4_check_word.py
tests/test_es.py
wikidict/convert.py
wikidict/gen_dict.py
wikidict/lang/es/__init__.py
wikidict/render.py

fix #1223: [ES] Add variant for verbs and adjectives

---

wikidict/lang/fr/arabiser.py

fix #1238: [FR] Update 'arabiser()' function

---

scripts/de-abk.py
scripts/de-lang_adjs.py
scripts/de-langs.py
scripts/el-langs.py
scripts/en-form-of.py
scripts/en-labels.py
scripts/en-langs.py
scripts/en-places.py
scripts/es-campos-semanticos.py
scripts/es-langs.py
scripts/fr-domain-templates.py
scripts/fr-langs.py
scripts/fr-regions.py
scripts/fr-temps-geologiques.py
scripts/pt-escopo.py
scripts/pt-gramatica.py
scripts/pt-langs.py
scripts/scripts_utils.py
wikidict/lang/fr/regions.py

fix #1236: Add timeout and retries to scripts, refactor http calls

---

scripts/en-labels.py
wikidict/lang/en/labels.py
wikidict/lang/fr/arabiser.py

fix #1260: SyntaxError in data update scrip

---

wikidict/lang/fr/template_handlers.py

[FR] Fix handling non-numeric values from the 'Unité' template

---

tests/test_fr.py
wikidict/lang/fr/template_handlers.py

fix #1296: [FR] Adapt 'composé de' support with a base, and a suffixe

---

wikidict/lang/fr/template_handlers.py

[FR] Support 'contexte' template

---

tests/data/fr/Turgeon.wiki
tests/test_fr.py
wikidict/lang/fr/__init__.py
wikidict/utils.py

[FR] Support 'R:Tosti' template

---

wikidict/lang/en/template_handlers.py

fix #1308: [EN] Fix 'given name' template support with multiple langs

---

wikidict/render.py

Fix mypy 0.971 errors

---

wikidict/lang/pt/__init__.py
wikidict/lang/pt/langs.py

fix #1340: [PT] Error with 'prenome'

---

wikidict/lang/ca/__init__.py

fix #1329:[CA] Support 'epònim' template

---

wikidict/lang/ca/__init__.py

fix #1291: [CA] Support 'calc semàntic' template

---

tests/test_ca.py
wikidict/lang/ca/__init__.py

[CA] Support 'format-augm' template

---

wikidict/lang/en/template_handlers.py

[EN] Adapt 'surname' output

---

tests/test_2_render.py
tests/test_ca.py
tests/test_en.py
wikidict/lang/ca/__init__.py
wikidict/lang/en/__init__.py
wikidict/render.py

fix #1371 #1370 #1369 [EN] [CA] fix pronunciation regexp, support [CA] 'm' and 'def-meta'

---

tests/data/es/ruego.wiki
tests/test_es.py
wikidict/render.py

[ES] Fix handling of word using the 'ES' model as head section

---

tests/test_es.py
wikidict/lang/es/__init__.py

[ES] Expand pronunciations support

---

wikidict/lang/es/__init__.py

[ES] Ignore 'relacionado' template

---

html/wikidict/user_functions.html
wikidict/lang/ca/__init__.py
wikidict/lang/de/__init__.py
wikidict/lang/el/__init__.py
wikidict/lang/en/__init__.py
wikidict/lang/es/__init__.py
wikidict/lang/fr/__init__.py
wikidict/lang/it/__init__.py
wikidict/lang/pt/__init__.py
wikidict/lang/ru/__init__.py
wikidict/lang/sv/__init__.py
wikidict/user_functions.py

New functions mostly to keep some uniformatization in genres, and pronunciations, code.

Introduce `flatten()`, and `uniq()` user functions

---

wikidict/lang/el/__init__.py
wikidict/lang/en/template_handlers.py

fix #1366: [EN] Fix 'place' template support

---

tests/test_fr.py
wikidict/lang/fr/__init__.py

[FR] Support 'Lang-ar' template

---

wikidict/convert.py

Remove variant normalization

---

tests/data/fr/base.html
tests/test_fr.py
wikidict/lang/fr/__init__.py

[FR] Adjust 'figuré' template ouput

---

wikidict/lang/el/__init__.py

[EL] Support more genders

---

tests/test_en.py
wikidict/lang/en/template_handlers.py

[EN] Support 'uder' template

---

scripts/en-labels.py
tests/test_en.py
tests/test_es.py
wikidict/lang/en/labels.py
wikidict/lang/es/__init__.py

fix #1439: [EN] Syntax error in scripts/en-labels.py

---

tests/data/en/humans.wiki
tests/data/en/memoized.wiki
tests/test_en.py
wikidict/lang/en/__init__.py
wikidict/render.py

[EN] Add support for variants

---

tests/test_ca.py
wikidict/lang/ca/__init__.py

[CA] Fix 'comp' support

---

tests/test_fr.py
wikidict/lang/fr/__init__.py

[FR] Fix "info lex" taking into account keyword parts

---

wikidict/utils.py

Fix parsing of external links with title

---

wikidict/lang/fr/template_handlers.py

[FR] Support symbols for the "lien-ancre-étym" template

---

tests/test_fr.py
wikidict/lang/fr/__init__.py

[FR] Fix "emploi" taking into account keyword arguments

---

wikidict/lang/fr/template_handlers.py

[FR] Handle the "m" argument from "abréviation" template

---

wikidict/lang/fr/template_handlers.py

[FR] Handle "texte" argument from "sigle" template

---

tests/test_4_check_word.py
wikidict/check_word.py

fix #1461: Add 'siècle2' HTML filter

---

wikidict/lang/fr/template_handlers.py

fix #1465: [FR] Handle 'équiv-pour' additionnal arguments

---

wikidict/lang/fr/template_handlers.py

fix #1460: [FR] Adapt 'composé de' output

---

wikidict/utils.py

Smarter magic-word filter

---

tests/test_4_check_word.py
wikidict/check_word.py
wikidict/lang/fr/template_handlers.py

fix #1493: fix siecle2 template and let check-word filter alone

---

wikidict/lang/fr/__init__.py
wikidict/lang/fr/template_handlers.py

fix #1492: [FR] Improve support for the 'term' template

---

scripts/en-labels.py
wikidict/lang/en/labels.py

fix #1510: [EN] Fix en-labels script

---

wikidict/lang/fr/template_handlers.py

[FR] Support "2e" template

---

wikidict/lang/fr/template_handlers.py

fix #1516: [FR] Adapt 'siecle' output

---

tests/test_ca.py
wikidict/lang/ca/__init__.py

[CA] Support "romanes" template

---

wikidict/lang/ca/template_handlers.py

[CA] Support "sigles de" template

---

tests/test_ca.py
wikidict/lang/ca/__init__.py

[CA] Support "fals tall" templates

---

tests/test_ca.py
wikidict/lang/ca/__init__.py
wikidict/lang/ca/template_handlers.py

[CA] Handle keyword arguments in "sinònim" template

---

tests/test_4_check_word.py
wikidict/check_word.py

[CA] Add custom filter for "sense accepcions" template

---

wikidict/lang/ca/__init__.py

[CA] Take into account "t" parameter in all templates

---

tests/test_pt.py
wikidict/lang/pt/__init__.py

[PT] Change double quote types in "llietimo" template

---

wikidict/lang/fr/template_handlers.py

fix #1547: [FR] Support '4e' template

---

wikidict/lang/fr/__init__.py

fix #1541: [FR] Fix 'la-note-ij' template

---

tests/test_pt.py
wikidict/lang/pt/__init__.py

fix #1564: [PT] Support "escopoObs." template

---

wikidict/lang/pt/__init__.py

[PT] Several fixes for "llietimo" template

---

tests/test_pt.py
wikidict/lang/pt/__init__.py

[PT] Support "confundir" template

---

wikidict/lang/en/__init__.py
wikidict/lang/es/__init__.py
wikidict/render.py

fix #1582: [EN] Support 'non-gloss', alias of 'non-gloss definition'

---

tests/test_4_check_word.py
wikidict/check_word.py

fix #1576: [PT] --check-word not working with anchors

---

wikidict/lang/pt/__init__.py
wikidict/user_functions.py

fix #1591: [PT] Handle implicit "trad" in "etimo" template

---

tests/test_4_check_word.py
wikidict/check_word.py

fix #1594: [PT] Add custom filter for "ligaçãoPalavraWdic" template

---

wikidict/lang/pt/__init__.py

fix #1596: [PT] Handle numeric keyword arguments in "llietimo" template

---

tests/test_pt.py
wikidict/lang/pt/__init__.py

[PT] Improve support for "l.s." template

---

wikidict/lang/pt/__init__.py

[PT] Support "grafiaPtbr" template, and similar

---

wikidict/lang/ca/__init__.py

[CA] Support "la" template, and other locales

---

tests/test_ca.py
wikidict/lang/ca/__init__.py

[CA] Support "claudàtors" template

---

wikidict/lang/ca/template_handlers.py

[CA] Support "g" template

---

docs/ca/README.md
tests/data/ca/expertes.wiki
tests/data/ca/halloweeniana.wiki
tests/test_ca.py
wikidict/lang/ca/__init__.py
wikidict/render.py

Fixes #1484
Total words on the Wiktionary: `374,193`
Total words in our dictionaries before that patch: `42,715`
Total words in our dictionaries after that patch: `368,860`
:champagne:

[CA] Add variant for verbs and adjectives

---

tests/test_en.py
wikidict/lang/en/__init__.py
wikidict/lang/en/template_handlers.py

fix #1525: [EN] Better support for 'IPAchar' template

---

tests/test_en.py
wikidict/lang/en/__init__.py

fix #1583: [EN] Support 'smallcaps' template

---

tests/test_en.py
wikidict/lang/en/__init__.py

fix #1584: [EN] Support 's' and 'sense' templates

---

wikidict/lang/en/template_handlers.py

fix #1598: [EN] Support 'onomatopoeic' template

---

wikidict/lang/fr/template_handlers.py

[FR] Handle "nom commun" in "lien-ancre-étym" template

---

wikidict/check_word.py
wikidict/lang/en/__init__.py
wikidict/lang/en/template_handlers.py

fix #1585: [EN] Support 'etydate' template

---

scripts/all-namespaces.py
wikidict/namespaces.py

Fixes #1608
@lasconic OK with such change, or do you see a way to retrieve that namespace alias automatically maybe?

[PT] Add "Imagem" to ignored namespaces

---

wikidict/lang/pt/__init__.py

[PT] Support "f" template, and similar

---

tests/test_2_render.py
wikidict/render.py
wikidict/utils.py

[ES] Fix a parsing issue

---

wikidict/lang/en/__init__.py
wikidict/lang/en/template_handlers.py

fix #1652: [EN] Error with Gamaliel

---

wikidict/lang/en/__init__.py
wikidict/lang/en/form_of.py
wikidict/lang/en/template_handlers.py

fix #1664: [EN] Support 'clipping' template

---

scripts/en-form-of.py
wikidict/lang/en/__init__.py
wikidict/lang/en/form_of.py
wikidict/lang/en/template_handlers.py

fix #1663: [EN] Support 'surf' template

---

wikidict/lang/__init__.py
wikidict/lang/ca/__init__.py
wikidict/lang/de/__init__.py
wikidict/lang/defaults.py
wikidict/lang/en/__init__.py
wikidict/lang/es/__init__.py
wikidict/lang/fr/__init__.py
wikidict/lang/sv/__init__.py
wikidict/render.py

A proposal to reduce intrusive code in `render.py`, and hopefully to ease variants management for each locale.

Refactor how we find variants

---

wikidict/lang/de/template_handlers.py

fix #1215: [DE] Support "Hebr" template, and similar

---

tests/test_es.py
wikidict/lang/es/__init__.py
wikidict/lang/es/template_handlers.py
wikidict/lang/fr/__init__.py
wikidict/lang/fr/ar_pronunciation.py

Fixes #1717
Fixes #1713
Fixes #1712
Also better test coverage for french ar-* templates

fix #1717: [ES] Better support for contracción template

---

tests/test_4_check_word.py
wikidict/check_word.py
wikidict/lang/es/__init__.py
wikidict/user_functions.py

fix #1710: [ES] Handle additionnal parameters for coord template

---

scripts/en-langs.py
wikidict/lang/en/labels.py
wikidict/lang/en/langs.py
wikidict/lang/fr/racines_arabes.py
wikidict/lang/fr/regions.py

fix #1772: update en-langs.py

---

scripts/all-namespaces.py
tests/data/ro/paronim.wiki
tests/test_ro.py
wikidict/lang/__init__.py
wikidict/lang/ro/__init__.py
wikidict/namespaces.py
wikidict/render.py

fix #1771: add romanian

---

docs/ro/README.md
wikidict/lang/ro/__init__.py

Related to #1771.
Courtesy of @drkoll :)

[RO] Update README, and some specific details

---

tests/data/ro/aventurierul.wiki
tests/data/ro/frumoasă.wiki
tests/data/ro/frumoși.wiki
tests/data/ro/portocale.wiki
tests/test_ro.py
wikidict/lang/ro/__init__.py
wikidict/render.py

[RO] Add variants, improve pronunciations

---

tests/data/ro/fi.wiki
tests/test_ro.py
wikidict/lang/ro/__init__.py
wikidict/render.py

[RO] Support sub-sub sections

---

scripts/en-langs.py

fix #1785: error in en-langs.py

---

tests/test_es.py
wikidict/lang/es/__init__.py

fix #1809: [ES] Fix support for 'ucf' template

---

scripts/en-labels.py
wikidict/lang/de/langs.py
wikidict/lang/en/labels.py

fix en-labels aliases

---

tests/test_sv.py
wikidict/lang/sv/__init__.py

[SV] Support "övrigatecken" template

---

wikidict/lang/it/__init__.py

[IT] Support "Sup2" template

---

docs/it/README.md

I have translated the page into Italian. 
Hyperlinks checked.
Text reviewed.

Italian Translation

---

wikidict/lang/fr/__init__.py

I added tests for #1849, and dicovered a trailing space was present.
Related to #1849.

[FR] Remove trailing space in 'ar-cf' template

---

.github/workflows/daily.yml
wikidict/utils.py

Fixes #1862.
I m not particularly proud of the code, but it seems to work for now.

[IT] Add word of the day support

---

wikidict/lang/it/__init__.py
wikidict/render.py

[IT] Enhance variants support

---

wikidict/lang/fr/template_handlers.py

fix #1852: [FR] Fix support for 'étyl' template with unknown lang

---

wikidict/lang/es/__init__.py

fix #1810: [ES] Support 'poblaciones' template

---

docs/ru/README.md

Fixes # 
This PR adds Russian translation of `Readme.md` file.

Russian translation for docs

---

wikidict/lang/pt/__init__.py

[PT] Support "etimo2" template

---

docs/ca/README.md

Translation of the Catalan doc

Translate Catalan doc

---

tests/test_ca.py
wikidict/lang/ca/__init__.py

[CA] Support "e-propi" template

---

wikidict/lang/fr/__init__.py

fix #1957: [FR] Support 'pron-recons' template

---

wikidict/lang/es/__init__.py
wikidict/utils.py

fix #1958: [ES] Ignore & filter out 'referencia' template

---

wikidict/lang/ca/template_handlers.py
wikidict/lang/de/template_handlers.py
wikidict/lang/defaults.py
wikidict/lang/en/template_handlers.py
wikidict/lang/es/template_handlers.py
wikidict/lang/fr/template_handlers.py
wikidict/lang/no/template_handlers.py
wikidict/lang/ru/template_handlers.py
wikidict/user_functions.py

fix #1964: Replace Dict by DefaultDict in extract_keywords

---

wikidict/lang/ca/__init__.py
wikidict/lang/ca/template_handlers.py

fix #1531: [CA] Handle '+word' in 'comp' template

---

wikidict/lang/ca/template_handlers.py

fix #1976: [CA] Fix support for 'comp' template with 3 parameters

---

wikidict/check_word.py
wikidict/lang/ca/__init__.py
wikidict/lang/ca/general.py
wikidict/lang/ca/ru_trans.py

fix #1978: [CA] Add transliteration support for RU

---

scripts/ca-langs.py
wikidict/lang/ca/__init__.py
wikidict/lang/ca/langs.py

fix #1974: [CA] Fix support for 'del-lang' template when lang is a group

---

wikidict/lang/es/__init__.py

[ES] Support "csem" template

---

.gitignore
README.md

Small readme update with python 3 env path activation and link to the ru issue

Small readme update with python 3 env path activation and link to the ru issue

---

tests/test_en.py
wikidict/lang/en/__init__.py

fix #2077: [EN] Support 'taxfmt' template

---

wikidict/lang/es/__init__.py
wikidict/lang/es/template_handlers.py

fix #2045: [ES] Issues to address

---

tests/test_en.py
wikidict/lang/ca/__init__.py
wikidict/lang/ca/template_handlers.py
wikidict/lang/de/__init__.py
wikidict/lang/de/template_handlers.py
wikidict/lang/defaults.py
wikidict/lang/en/__init__.py
wikidict/lang/en/template_handlers.py
wikidict/lang/es/__init__.py
wikidict/lang/es/template_handlers.py
wikidict/lang/fr/__init__.py
wikidict/lang/fr/template_handlers.py
wikidict/lang/no/__init__.py
wikidict/lang/no/template_handlers.py
wikidict/lang/ru/__init__.py
wikidict/lang/ru/template_handlers.py

[EN] Full support for "ISO 639" template

---

wikidict/lang/ca/template_handlers.py

fix #2111: [CA] Support 'grafia' template

---

.github/workflows/auto-update-data.yml
README.md
requirements-tests.txt
scripts/__main__.py

Bonus point: auto-formatting thanks to `ruff-api`!
Fixes #2122

fix: Improve auto-update scripts robustness

---

wikidict/lang/en/template_handlers.py

[EN] Fix support for "ISO 639" template

---

wikidict/lang/no/__init__.py

[NO] Missing support for several langs

---

tests/test_el.py
wikidict/lang/el/__init__.py

[EL] Support "ετικ" and "γρ" templates

---

scripts/en-labels.py

[EN] Deal with zh labels

---

wikidict/lang/pt/__init__.py

[PT] Support "étimo junção" template

---

tests/test_en.py
wikidict/lang/en/__init__.py

[EN] Add the infl of template to variants

---

tests/data/es/bicicleta.wiki
tests/test_en.py
tests/test_es.py
wikidict/render.py
wikidict/utils.py

fix: clean-up namespaces containing brackets and tags

---

tests/test_en.py
wikidict/lang/en/template_handlers.py

[EN] Parse gender string

---

tests/test_0_download.py
tests/test_4_check_word.py
wikidict/__main__.py
wikidict/check_word.py
wikidict/check_words.py
wikidict/convert.py
wikidict/download.py
wikidict/find_templates.py
wikidict/lang/ca/grc_trans.py
wikidict/lang/defaults.py
wikidict/parse.py
wikidict/render.py
wikidict/utils.py

It also allowed to remove our own threading lock as the logging module is already thread-safe: https://docs.python.org/3/library/logging.html#thread-safety
Fixes #1616

feat: make use of a proper logger

---

wikidict/lang/de/__init__.py
wikidict/lang/de/template_handlers.py

[DE] Support "Literatur" template

---

wikidict/lang/de/template_handlers.py

[DE] Support "Lit-Bahlow" template

---

wikidict/lang/el/__init__.py
wikidict/lang/el/template_handlers.py

[EL] Support "μτφδ" template

---

wikidict/render.py

fix: Clean-up HTML tags from variants

---

wikidict/lang/en/template_handlers.py

fix #2236: [EN] Fix support for 'affix' template

---

scripts/en-langs.py

fix #2265: Error with en-langs.py script

---

wikidict/convert.py

fix: change the default multiprocessing start method

---

.github/workflows/tests.yml

If we want to welcome contributions, and core developers to be able to actually work on the project, then this is the minimum we should do. It will highlight errors early in our processes.
Related #1054.

feat(ci): run tests on macOS

---

wikidict/lang/el/template_handlers.py

fix #2340: [EL] Support 'παθ' template

---

wikidict/convert.py
wikidict/utils.py

Inspired by the dicsussion on https://github.com/ilius/pyglossary/issues/624.

[EO] fix Kindle support

---

wikidict/lang/defaults.py

fix #2350:  Fix support for 'W' template

---

wikidict/lang/fr/template_handlers.py

fix #2351: [FR] Fix support for 'composé de' template

---

wikidict/lang/fr/__init__.py

fix #2353: [FR] Fix support for 'diminutif' template

---

wikidict/convert.py

fix: dynamically remove words based on characters count

---

wikidict/convert.py

feat(mobi): remove words based on characters count only + optimizations

---

.gitignore
tests/data/fr/djed.wiki
tests/test_3_convert.py
wikidict/convert.py

fix(stardict): missing image files

---

README.md

Add KOReader dictionary installation instructions to README

---

README.md

Explain in more detail the installation of dictionaries on koreader

---

wikidict/render.py

fix multiprocessing on macOS
